// front-react/src/views/home/Home.jsx
import React, { useState} from 'react';
import './Home.css';

// Heact Hooks
export default (props) => {
	// two-way data binding utiliza o useState
	let [legenda, setLegenda] = useState('Estou no React');

	function resetLegenda() {
		setLegenda('Estou no React');
	}

	// two way data bind >>>> e => setLegenda(e.target.value)
	return (
		<div className="home">
			<h1>Hello World React!!</h1>
			<p>{props.msg}</p>
			<h2>{legenda}</h2>
			<input type="text" value={legenda} onChange={ e => setLegenda(e.target.value) } />
			<button onClick={resetLegenda}>Reset Legenda</button>
		</div>
	)
}

// front-vue/src/views/home/Home.vue
<template>
	<div>
		<h1>Componente Home</h1>
		<p>{{ msg }}</p>
		<h2>{{ legenda }}</h2>
		<input type="text" v-model="legenda">
		<button @click="resetLegenda">Reset Legenda</button>
	</div>
</template>

<script>
export default {
	props: ['msg'],
	data: function () {
		return {
			legenda: 'Estou no Vue'
		}
	},
	methods: {
		resetLegenda() {
			this.legenda = 'Estou no Vue';
		}
	}
}
</script>

<style>

</style>
