// front-angular/src/app/views/home/home.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  @Input() msg;
  legenda: string = 'estou no Angular';

  constructor() { }

  ngOnInit(): void {
  }

  resetLegenda(): void {
    // console.log('Evento de click do angular!');
    // one way data binding
    this.legenda = 'estou no Angular';
  }

}

<p>Angular Componente Home</p>
<p>{{ msg }}</p>
<p>{{ legenda }}</p>

<!-- One way data binding -->
<!--<input type="text" [value]="legenda"> -->
<!-- Two way data binding -->
<input type="text" [(ngModel)]="legenda">

<button (click)="resetLegenda()">Reset Legenda</button>

// front-react/src/views/home/Home.jsx
import React, { useState} from 'react';
import './Home.css';

// Heact Hooks
export default (props) => {
	// two-way data binding utiliza o useState
	let [legenda, setLegenda] = useState('Estou no React');

	function resetLegenda() {
		setLegenda('Estou no React');
	}

	// two way data bind >>>> e => setLegenda(e.target.value)
	return (
		<div className="home">
			<h1>Hello World React!!</h1>
			<p>{props.msg}</p>
			<h2>{legenda}</h2>
			<input type="text" value={legenda} onChange={ e => setLegenda(e.target.value) } />
			<button onClick={resetLegenda}>Reset Legenda</button>
		</div>
	)
}
